### ISSUE TITLE
Got  'node not found'

### ISSUE THREAD

**Issue by Tech-User42** [HazemMeqdad/lavaplayer#20]
Hi i started to use your library to play music and i got that error

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/lightbulb/app.py", line 1154, in invoke_application_command
    await context.invoke()
  File "/home/pi/.local/lib/python3.9/site-packages/lightbulb/context/base.py", line 292, in invoke
    await self.command.invoke(self)
  File "/home/pi/.local/lib/python3.9/site-packages/lightbulb/commands/base.py", line 544, in invoke
    await self(context, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/lightbulb/commands/base.py", line 459, in __call__
    return await self.callback(context, **kwargs)
  File "/home/pi/M.A.R.I.O.N/test_bot/bot.py", line 147, in cmd_play_voice
    await lavalink.play(ctx.guild_id, result[0], ctx.author.id)  # play the first result
  File "/home/pi/.local/lib/python3.9/site-packages/lavaplayer/client.py", line 295, in play
    raise NodeError("Node not found", guild_id)
lavaplayer.exceptions.NodeError: ('Node not found', 791009507126804511)`

Here is my code 

```bot.command() # PLAY COMMAND
@lightbulb.add_cooldown(15.0, 1, lightbulb.UserBucket)
@lightbulb.add_checks(lightbulb.owner_only)
@lightbulb.option("musique","Ce que vous souhaitez faire lire à M.A.R.I.O.N") # Option definition 1) --> the name of the option 2) --> The description of the option
@lightbulb.command("play", "Connecter M.A.R.I.O.N")  # Command definition 1) --> the name of the command 2) --> The description of the command
@lightbulb.implements(lightbulb.SlashCommand) 
async def cmd_play_voice(ctx: lightbulb.SlashContext):
    await ctx.respond(ctx.member.nickname)

    query = ctx.options.musique  # get query from options
    result = await lavalink.auto_search_tracks(query)  # search for the query
    if not result:
        await ctx.respond("not found result for your query")
        return
    
    # Playlist
    if isinstance(result, lavaplayer.PlayList):
        await lavalink.add_to_queue(ctx.guild_id, result.tracks, ctx.author.id)
        await ctx.respond(f"added {len(result.tracks)} tracks to queue")
        return 
    print(result[0])
    print(ctx.author.id)
    print(ctx.guild_id)
    await lavalink.play(ctx.guild_id, result[0], ctx.author.id)  # play the first result
    await ctx.respond(f"[{result[0].title}]({result[0].uri})")  # send the embed```
    
    If you need i can give you the complete file

**Comment by HazemMeqdad** [comment]
welcome bro this error because a lavalink need to connected info you need to add this functions `raw_voice_server_update` & `raw_voice_server_update` in this events `hikari.VoiceStateUpdateEvent` & `VoiceServerUpdateEvent`
like this:
```py
# On voice state update the bot will update the lavalink node
@bot.listen(hikari.VoiceStateUpdateEvent)
async def voice_state_update(event: hikari.VoiceStateUpdateEvent):
    await lavalink.raw_voice_state_update(event.guild_id, event.state.user_id, event.state.session_id, event.state.channel_id)

@bot.listen(hikari.VoiceServerUpdateEvent)
async def voice_server_update(event: hikari.VoiceServerUpdateEvent):
    await lavalink.raw_voice_server_update(event.guild_id, event.endpoint, event.token)
```

**Comment by Tech-User42** [comment]
Hi thanks for your fast response, iv added your code but it return again node not found here is my complete code


```
import os
import hikari
import lightbulb
import lavaplayer

def make_embed(title,description,color="#f01202",thumbnail=None,footer="M.A.R.I.O.N v 0.0.2"):
    embed = hikari.Embed(title=title, description=description,color=color)
    #embed.add_field("Field name", "Field content (value)")
    if thumbnail:
        embed.set_thumbnail("https://i.imgur.com/EpuEOXC.jpg")
    embed.set_footer("This is the footer")
    return embed

bot = lightbulb.BotApp(
    os.environ["TOKEN"],
    default_enabled_guilds=int(os.environ["DEFAULT_GUILD_ID"]),
    help_slash_command=True ,
    intents=hikari.Intents.ALL,
)

lavalink = lavaplayer.LavalinkClient(
    host="localhost",
    port=2333,
    password="youshallnotpass",
    user_id=123
)




################################################
####### ERROR HANDLING AND PERM RESPONSE #######
################################################

@lavalink.listen(lavaplayer.TrackStartEvent)
async def track_start_event(event: lavaplayer.TrackStartEvent):
    logging.info(f"start track: {event.track.title}")

@lavalink.listen(lavaplayer.TrackEndEvent)
async def track_end_event(event: lavaplayer.TrackEndEvent):
    logging.info(f"track end: {event.track.title}")

@lavalink.listen(lavaplayer.WebSocketClosedEvent)
async def web_socket_closed_event(event: lavaplayer.WebSocketClosedEvent):
    logging.error(f"error with websocket {event.reason}")




@bot.listen(lightbulb.SlashCommandInvocationEvent)
async def on_command(event: lightbulb.SlashCommandInvocationEvent):
    print(f"La commande suivante à été executée `{event.context.command.name}`.")
@bot.listen(lightbulb.CommandErrorEvent)
async def on_error(event: lightbulb.CommandErrorEvent) -> None:
    if isinstance(event.exception, lightbulb.CommandInvocationError):
        await event.context.respond(f"Une erreur s'est produite :confused: `{event.context.command.name}`.")
        raise event.exception

    # Unwrap the exception to get the original cause
    exception = event.exception.__cause__ or event.exception

    if isinstance(exception, lightbulb.NotOwner):
        await event.context.respond("Vous n'êtes pas le propriétaire du bot, vous ne pouvez pas faire cela !")
    elif isinstance(exception, lightbulb.CommandIsOnCooldown):
        await event.context.respond(f"Cette commande à un cooldown, vous pourrez la refaire dans  `{exception.retry_after:.2f}` secondes.")
    else:
        raise exception

@bot.listen(hikari.VoiceStateUpdateEvent)
async def voice_state_update(event: hikari.VoiceStateUpdateEvent):
    await lavalink.raw_voice_state_update(event.guild_id, event.state.user_id, event.state.session_id, event.state.channel_id)

@bot.listen(hikari.VoiceServerUpdateEvent)
async def voice_server_update(event: hikari.VoiceServerUpdateEvent):
    await lavalink.raw_voice_server_update(event.guild_id, event.endpoint, event.token)
################################################
##### COMMAND DEFINITION AND FUNCTION DEF ######
################################################

@bot.command() # SAY COMMAND
@lightbulb.add_cooldown(15.0, 1, lightbulb.UserBucket)
@lightbulb.add_checks(lightbulb.owner_only, lightbulb.has_roles(879645790858014720))
@lightbulb.option("text","Ce que vous souhaitez faire dire à M.A.R.I.O.N") # Option definition 1) --> the name of the option 2) --> The description of the option
@lightbulb.command("say", "Faire dire quelque chose à  M.A.R.I.O.N") # Command definition 1) --> the name of the command 2) --> The description of the command
@lightbulb.implements(lightbulb.SlashCommand) 
async def cmd_say(ctx: lightbulb.SlashContext):
    print(dir(ctx))
    await ctx.respond(make_embed("Message de l'administration",ctx.options.text,"#f01202"))




@bot.command() # JOIN VOICE CHANNEL COMMAND
@lightbulb.add_cooldown(15.0, 1, lightbulb.UserBucket)
@lightbulb.add_checks(lightbulb.owner_only)
@lightbulb.command("join", "Connecter M.A.R.I.O.N") # Command definition 1) --> the name of the command 2) --> The description of the command
@lightbulb.implements(lightbulb.SlashCommand) 
async def cmd_join_voice(ctx: lightbulb.SlashContext):
    await ctx.respond(ctx.member.nickname)
    states = bot.cache.get_voice_states_view_for_guild(ctx.guild_id)
    voice_state = [state async for state in states.iterator().filter(lambda i: i.user_id == ctx.author.id)]
    try:
        await bot.update_voice_state(ctx.guild_id, voice_state[0].channel_id)
        await ctx.respond("Je suis là ! :wink:")
    except:
        await ctx.respond("Vous n'êtes pas dans un salon vocal :confused:")
        
        
@bot.command() # LEAVE VOICE CHANNEL COMMAND
@lightbulb.add_cooldown(15.0, 1, lightbulb.UserBucket)
@lightbulb.add_checks(lightbulb.owner_only)
@lightbulb.command("leave", "Connecter M.A.R.I.O.N")  # Command definition 1) --> the name of the command 2) --> The description of the command
@lightbulb.implements(lightbulb.SlashCommand) 
async def cmd_leave_voice(ctx: lightbulb.SlashContext):
    await ctx.respond(ctx.member.nickname)
    try:
        await bot.update_voice_state(ctx.guild_id, None)
        await ctx.respond("A bientôt ! :wink:")
    except:
        await ctx.respond("Vous n'êtes pas dans un salon vocal :confused:")



@bot.command() # PLAY COMMAND
@lightbulb.add_cooldown(15.0, 1, lightbulb.UserBucket)
@lightbulb.add_checks(lightbulb.owner_only)
@lightbulb.option("musique","Ce que vous souhaitez faire lire à M.A.R.I.O.N") # Option definition 1) --> the name of the option 2) --> The description of the option
@lightbulb.command("play", "Connecter M.A.R.I.O.N")  # Command definition 1) --> the name of the command 2) --> The description of the command
@lightbulb.implements(lightbulb.SlashCommand) 
async def cmd_play_voice(ctx: lightbulb.SlashContext):
    await ctx.respond(ctx.member.nickname)

    query = ctx.options.musique  # get query from options
    result = await lavalink.auto_search_tracks(query)  # search for the query
    if not result:
        await ctx.respond("not found result for your query")
        return
    
    # Playlist
    if isinstance(result, lavaplayer.PlayList):
        await lavalink.add_to_queue(ctx.guild_id, result.tracks, ctx.author.id)
        await ctx.respond(f"added {len(result.tracks)} tracks to queue")
        return 
    print(result[0])
    print(ctx.author.id)
    print(ctx.guild_id)
    await lavalink.play(ctx.guild_id, result[0], ctx.author.id)  # play the first result
    await ctx.respond(f"[{result[0].title}]({result[0].uri})")  # send the embed



def run():
    if os.name != "nt":
        import uvloop
        uvloop.install()
    lavalink.connect()
    bot.run()
```

**Comment by HazemMeqdad** [comment]
replace a `user_id=123` and use your bot id

**Comment by Tech-User42** [comment]
I did that so now the bot can return the song url and name in a message but the bot dont play the audio, i got that in error

```
La commande suivante à été executée `play`.
E 2022-03-25 09:54:27,962 lavaplayer.ws: Not connected to websocket
```

And on the java console i got that 

```
2022-03-25 09:54:23.549  INFO 6534 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 52 ms
2022-03-25 09:54:23.895  INFO 6534 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Something in the way"
2022-03-25 09:54:27.727  INFO 6534 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Something in the way
```

**Comment by HazemMeqdad** [comment]
check if you delete something or `lavalink.run()`

**Comment by Tech-User42** [comment]
What do you mean by ` lavalink.run()` ? i cant find anything related to that

**Comment by HazemMeqdad** [comment]
its to make connect to lavalink server and start websocket

**Comment by Tech-User42** [comment]
I added `lavalink.run()`


in here 

```
def run():
    if os.name != "nt":
        import uvloop
        uvloop.install()
    print(dir(lavalink))
    lavalink.connect()
    lavalink.run()
    bot.run()
```

And i got that 

```
File "/home/pi/M.A.R.I.O.N/test_bot/bot.py", line 161, in run
    lavalink.run()
AttributeError: 'LavalinkClient' object has no attribute 'run'
```

**Comment by HazemMeqdad** [comment]
just remove a `lavalink.run()`

**Comment by Tech-User42** [comment]
I removed it and when i run the /join command i got that in the bot 

```
La commande suivante à été executée `join`.
E 2022-03-25 17:50:15,023 lavaplayer.ws: Not connected to websocket
```

**Comment by HazemMeqdad** [comment]
brother please check to host name or port or password

**Comment by Tech-User42** [comment]
Here is my application.yml 

```
server: # REST and WS server
  port: 2333
  address: "127.0.0.1"

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
```

And here is my lavalink config

```
lavalink = lavaplayer.LavalinkClient(
    host="127.0.0.1",
    port=2333,
    password="youshallnotpass",
    user_id=888149518388981813
)
```
